### ISSUE TITLE
hi brother 

### ISSUE THREAD

**Issue by alisaleh1984** [Pitmov/tokenizing-autocomplete#1]
i update some code for your plugin 
css to work on apex 5.1
.token-input-dropdown 
{
   
  position: relative !important;
    
}

ul.token-input-list
{
 z-index: 22 !important ;
 font-size: 12px;
 font-family: ARIAL  !important ;
}

**Comment by Pitmov** [comment]
Hi, thanks for pointing on that. Looks like this is only css changes and it can be different for different APEX themes, so I don't think that is good solution and it can produce other issues in apps. Anyway I didn't change anything for this plugins for three years, so feel free to use and change it as you want.
